# - Try to find LibQGit2
# Once done this will define
#
#  QGIT2_FOUND - system has LibQGit2
#  QGIT2_INCLUDE_DIR - the LibQGit2 include directory
#  QGIT2_LIBRARY


FIND_PATH(QGIT2_INCLUDE_DIR NAMES QGit2 PATH_SUFFIXES QGit2)

FIND_LIBRARY(QGIT2_LIBRARY NAMES qgit2)

IF (QGIT2_INCLUDE_DIR AND QGIT2_LIBRARY)
  SET(QGIT2_FOUND TRUE)
ENDIF (QGIT2_INCLUDE_DIR AND QGIT2_LIBRARY)


IF (QGIT2_FOUND)
  IF (NOT QGIT2_FIND_QUIETLY)
    MESSAGE(STATUS "Found QGit2: ${QGIT2_LIBRARY}")
  ENDIF (NOT QGIT2_FIND_QUIETLY)
ELSE (QGIT2_FOUND)
  IF (QGIT2_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find LibQGit2 <https://projects.kde.org/projects/playground/libs/libqgit2/>")
  ENDIF (QGIT2_FIND_REQUIRED)
ENDIF (QGIT2_FOUND)
